unchained/app_unchained/urls.py
from django import urls
from django.urls import path
from . import views

app_name="app_unchained"
urlpatterns=[
    path('', views.index, name='index'),

    path('create', views.create_index, name='create'),
    path('question/<int:question_id>/', views.detail, name='detail'),
    path('update/<int:id>', views.update_view, name="update" ),
    path('delete/<int:id>', views.delete_view, name='delete' ),

    path('chat', views.chat, name='chat'),
    path('chat/<str:room_name>/', views.room, name='room'),
]

unchained/unchained/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app_unchained.urls')),
    path('admin/', admin.site.urls),
]

unchained/app_unchained/models.py
from django.db import models
from django import forms

class Question(models.Model):
    text = models.CharField(max_length=200)
       
class QuestionForm(forms.ModelForm):
   class Meta:
     model = Question
     fields = '__all__'

unchained/app_unchained/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from .models import Question,QuestionForm
from django.shortcuts import render

def band_create(request):
   form = QuestionForm()
   return render(request,
            'app_unchained/create.html',
            {'form': form})

def index(request):
    questions = Question.objects.all()
    context = {'questions': questions,}
    return render(request, 'app_unchained/index.html', context)

def create_index(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form = QuestionForm()
    return render(request,
            'app_unchained/create.html',
            {'form': form})

def delete_view(request, id):
    obj = get_object_or_404(Question, id = id)
    obj.delete()
    return HttpResponseRedirect("/")

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'app_unchained/detail.html', {'question': question})

def update_view(request, id):
    context ={}
    obj = get_object_or_404(Question, id = id)
    form = QuestionForm(request.POST or None, instance = obj)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    context["form"] = form
 
    return render(request, "app_unchained/update.html", context)

def chat(request):
    return render(request, 'app_unchained/chat.html')

def room(request, room_name):
    return render(request, 'app_unchained/room.html', {
        'room_name': room_name
    })

unchained/app_unchained/templates/app_unchained/chat.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

unchained/app_unchained/templates/app_unchained/create.html
{% block content %}

 <h1>Create new question</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

{% endblock %}

unchained/app_unchained/templates/app_unchained/delete.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this question ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

unchained/app_unchained/templates/app_unchained/detail.html
{% block content %}
 <h1>Details</h1>
 <p> Id : {{ question.id }}</p>
 <p> Text : {{ question.text }}</p>
 <a href="{% url 'app_unchained:update' question.id %}" > <button>Update</button></a>
 <a href="{% url 'app_unchained:delete' question.id %}" > <button>Delete</button></a>
{% endblock %}

unchained/app_unchained/templates/app_unchained/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APP UNCHAINED</title>
</head>
<body>
    <h1>Django is legendary</h1>
    <a href="/admin"><button>Admin</button></a>
    <a href="{% url 'app_unchained:chat' %}"><button>Chat</button></a>
    <h2>Liste des question</h2>
    {% if questions %}
    <ul>
        {% for question in questions %}
        <li>
           {{question.text}}<a href="{% url 'app_unchained:detail' question.id %}"> <button class="button">Aller au détail</button></a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url 'app_unchained:create' %}" ><button>Créer une question</button></a>
</body>
</html>

unchained/app_unchained/templates/app_unchained/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        // onmessage - An event listener to be called when a message is received from the server.
        chatSocket.onmessage = function(e) {
            // JSON.parse() converts the JSON object back into the original object,
            // then examine and act upon its contents.
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        // onclose - An event listener to be called when the connection is closed.
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;

            // Send the msg object as a JSON-formatted string.
            chatSocket.send(JSON.stringify({
                'message': message
            }));

            // Blank the text input element, ready to receive the next line of text from the user.
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

unchained/app_unchained/templates/app_unchained/update.html
{% block content %}

<h1>Create new question</h1>

<form action="" method="post" novalidate>
 {% csrf_token %}
 {{ form }}
 <input type="submit" value="Submit">
</form>

{% endblock %}